services:
  scorecard:
    build: .
    container_name: scorecard
    ports:
      - "3005:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      SOURCE_SPREADSHEET: /app/assets/Scorecard Template.xlsx
      SCORECARD_WEEKLY_SHEET: Weekly
      SCORECARD_MONTHLY_SHEET: Monthly
    volumes:
      - ./assets:/app/assets
      - ./.cache:/app/.cache
    restart: unless-stopped
